### ISSUE TITLE
docker-compose build 执行错误

### ISSUE THREAD

**Issue by neconano** [cjeruen/zan-docker#1]
系统 
ubuntu16.4.2
docker 17.05ce
docker compose 1.14
执行docker-compose build报错

install failed
ERROR: Service 'php_zan_http' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y     libfreetype6-dev     libjpeg62-turbo-dev     libpng12-dev     libmcrypt-dev     libcurl4-openssl-dev     libssl-dev     && docker-php-ext-install -j$(nproc) mcrypt      && docker-php-ext-install -j$(nproc) pdo_mysql     && docker-php-ext-install -j$(nproc) gd     && apt-get install -y libldb-dev libldap2-dev     && ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so     && ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so     && docker-php-ext-install -j$(nproc) ldap     && apt-get install -y libc-client-dev libkrb5-dev     && docker-php-ext-configure imap --with-kerberos --with-imap-ssl     && docker-php-ext-install imap     && pecl install redis     && docker-php-ext-enable redis     && pecl install apcu     && docker-php-ext-enable apcu     && cd /opt/hiredis-0.13.3     && make && make install && ldconfig     && ln -s /usr/local/lib/libhiredis.so /usr/local/lib/libhiredis_linux.so     && ln -s /usr/local/lib/libhiredis.a /usr/local/lib/libhiredis_linux.a     && docker-php-ext-install -j$(nproc) lz4     && docker-php-ext-install -j$(nproc) sockets     && docker-php-ext-configure zan --enable-sockets --enable-async-redis  --enable-openssl     && docker-php-ext-install -j$(nproc) zan     && rm -r /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by cjeruen** [comment]
当前版本已经解决
